version: "3.9"
services:
  backend:
    image: sajal/expense-extractor-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
  frontend:
    image: sajal/expense-extractor-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
  reverse-proxy:
    image: nginx:latest
    depends_on:
      - frontend
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8002:8002
