version: "3.9"
services:
  backend:
    image: sajal/expense-extractor-backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:80"
  frontend:
    image: sajal/expense-extractor-frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"
